### ISSUE TITLE
IBP flag

### ISSUE THREAD

**Issue by bahmandehnadi** [mppmu/secdec#2]
Hey, I have a multidimensional integral and I wish to turn off the integration by part routine for specific integration variables. It seems that the only possible option is to use "ibp_power_goal = -np.inf".  However this is a global flag for all integration variables. The question is: would it be possible to turn off the  IBP only for a subset of integration variables?

**Comment by jPhy** [comment]
This enhancement should only require minor changes to the code. I will have a look.
